name: ybs
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  flutter_map_math: ^0.2.3
  path: ^1.9.1
  path_provider: ^2.1.5
  free_map: ^2.3.0
  flutter_location_search: ^2.0.0
  url_launcher: ^6.3.1
  timeline_tile: ^2.0.0
  flutter_tts: ^4.2.3
  flutter_foreground_task: ^9.1.0
  minimize_flutter_app: ^0.0.2
  flutter_local_notifications: ^19.3.0
  flutter_native_splash: ^2.4.6
  blinking_text: ^1.0.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/ybs_dump.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Z01-Umoe002
      fonts:
        - asset: assets/fonts/Z01-Umoe002-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: false
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: false
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash.png
  android_12:
    image: assets/icons/splash.png
    color: "#ffffff"
  android: true
  ios: false
  web: false
